### ISSUE TITLE
XML output format

### ISSUE THREAD

**Issue by xeals** [xeals/signal-back#3]
[SMS Backup & Restore](https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore) is a popular app for backing up the system SMS database, and Signal used to be able to produce outputs compatible with it. This will probably be my first endeavour.

- [x] Parse SMS and MMS transactions
- [x] Write SMS instances
- [ ] Write MMS instances
- [ ] Write MMS attachments?
- [x] SMS Backup & Restore can actually fully restore the SMS database with it

**Comment by xeals** [comment]
3c02d0a503c5caa3c9b2da40e5df621553bafba6 fixes type exports, so now the database is actually revivable.

Biggest issue that I can see at the moment is that timestamps are a bit broken.

**Comment by DaveKap** [comment]
Since MMS isn't being written, does that explain why my 220MB backup only gets decoded into a 5MB backup?

**Comment by xeals** [comment]
It would be a primary reason, yes. MMS -- even their textual components -- aren't currently being used.

**Comment by DaveKap** [comment]
Okay. I tried to merge the backup and so very little of it actually transferred I wasn't sure what was going on. I'll do it again and see if it works but otherwise I'll write a new ticket for help figuring out what's going wrong.

**Comment by timewasted** [comment]
I just wanted to drop a line to say that I'm working on adding support for MMS and their attachments.  The code is mostly written and I'm currently playing with it locally to see what issues crop up.  Once I'm reasonably happy with things I'll send you a pull request.

**Comment by timewasted** [comment]
No need to thank me, especially since you did all the hard work.  I'm just doing a bit of minor plumbing, since you already had most of the pieces available.

The only thing that I haven't been able to figure out is how to make MMS that you sent not show "From: Hidden sender address" when viewing the message info in Android Messages.  As much as it offends my desire to have everything pristine, I'm unlikely to spend (much) more time chasing it down since SMS Backup and Restore backing up and then restoring to Android Messages has the same behavior.

I'm doing one last restore of my 399MB Signal backup (which is 528MB in XML format) to check for any last issues, then I'll push everything up.  Unfortunately my guinea pig device is a SLOW Nexus 4, so it'll be restoring for a while.  I don't expect any issues, though!

**Comment by DaveKap** [comment]
I haven't done any work at all other than failing to merge my signal history.

**Comment by timewasted** [comment]
Hah, I totally spaced out on who I was replying to.  Oh well.

@xeals I created a pull request to add MMS support: #32

**Comment by brightbluejay** [comment]
Hi, is this fixed? I'm having just a 1kb file output in XML and no messages in the file? CSV export works though.

signal-back v0.1.6
proto commit: d6610f0

Thank you
