### ISSUE TITLE
What password?

### ISSUE THREAD

**Issue by novoid** [xeals/signal-back#33]
Hi,
The README talks about PASS but does not explain where does the password comes from. I am using Signal for years and did not set any password within Signal for Android. Do I have an empty password, just requiring to press Return when asked for the PASS?

(I can't confirm that an empty password works since I got panic errors in any case which I'd write into a separate issue, if they are not related to my password issue.)

**Comment by xeals** [comment]
`signal-back` decrypts the encrypted backups in recent versions of Signal. To enable these backups, the app will provide you with a 30-digit password that you can use to restore them. This is the same password that you'll need to provide `signal-back`.

The panic errors are probably due to an incorrect password; because it's encrypted, there's no difference to the program between an invalid file and an incorrectly decrypted one.

**Comment by novoid** [comment]
Thanks for your help. When I saw a screenshot of it, I now remember that there was a password I had to write down.
Checking and extracting now works like a charm. Thank you very much for your wonderful tool!
I created a small pull request on improving the Readme such that somebody who forgot about the password might remember.
